### ISSUE TITLE
Add support for marking interviews as completed

### ISSUE THREAD

**Issue by YiHern-Lee** [AY2122S2-CS2103-W17-4/tp#122]
### Under interview:
User should be able to apply commands on interviews to mark the interview and transition the interview between 3 stages.
Pending -> Pass & offer/Fail -> Accept/Reject offer

### Under applicant:
After applicant accepts job offer, applicant's profile should reflect the new job title.

### Under position:
When offering a job to applicant, position should keep track the number of offers handed out. Number of offers handed out should be <= number of offers.
When a candidate accepts an offer, number of openings and offers should decrement by 1. 
When number of openings is 0, then all pending interviews for that position should be automatically failed. 

Features to implement
- [ ] Marking interview based on stages (Pending, Passed/Failed interview, Candidate accept/reject offer)
- [ ] Positions keep track of the number of offers handed out (make sure that number of offers <= openings)
- [ ] Cascading auto fail for all interviews when positions have no more openings
- [ ] Update applicant status (not hired/new job title)
