### ISSUE TITLE
List command with sorting and filtering options

### ISSUE THREAD

**Issue by likeabowx** [AY2122S2-CS2103-W17-4/tp#146]
To upgrade `ListCommand` to accept parameters for sorting and/or filtering the list before displaying. The format of the command will be `list -X f\[filterType] a\[filterArgument] s\[sort-key]`.

- [x] Edit `ListCommandParser.java` to accept the parameters
- [x] Edit `ListXYZCommand.java`  to call the different methods to filter and/or sort the list 	
- [x] Implement filter by @likeabowx 
- [x] Implement sort by @khoahre123
